### PR TITLE
test 4.1.0 version of riot-jest-transformer

### PR DESCRIPTION
**Pull request by tompascall**
It is just a sample how you could use Riot pre-processors with riot-jest-transformer.

You can read about the new functionality in the updated readme of the transformer:  https://github.com/tompascall/riot-jest-transformer#setting-up-jest-config-file

pagetwo.spec.js can be run after some modification (It seems that riot just does not support mixin so I had to comment it out, and I had to register the component before mounting).

I forced the very first test case, just for the prove of concept.

### CODE REVIEW

**Comment by Acesmndr** [comment]
It's unfortunately not working at my end here. Could you try running `yarn test:views`? The `jest.config.js` is passing type and name in registrations but not the registrationCb as it's a function. I checked by logging onto the console from the `riot-jest-transformer` in my node_modules and saw that only `[ { type: 'css', name: 'scss' } ]` is logged when I printed out the registration options. 
image
And since registrationCb is no longer a function and isn't passed it's failing.

Then I tried disabling the validation check in pre-processors.js for the registationCb and passing in the registering scss code manually through the pre-processors file like:

```js

const registerPreProcessors = (config) => {
  const registrationOptions = getRegistrationOptions(config);
  registrationOptions = Object.assign({}, registrationOptions, {
    registrationCb: (code, { options }) => {
                  console.log(code);
                    const { file } = options
                    console.log('Compile the sass code in', file)
                    const {css} = sass.renderSync({
                      data: code
                    });
                    return {
                      code: css.toString(),
                      map: null
                    }
                }
  })
  if (registrationOptions) {
    tryRegistrations(registrationOptions);
  }
};

exports.getRegistrationOptions = getRegistrationOptions;
exports.tryRegistrations = tryRegistrations;
exports.registerPreProcessors = registerPreProcessors;
```

Then it fails like
image

Currently the view tests in the repo are disabled and thus the tests are passing. `yarn test` command doesn't test the riot specific code right now.

**Comment by tompascall** [comment]
Could you create a branch that I could check?

**Comment by Acesmndr** [comment]
@tompascall I've updated my branch, you could merge it to see the tests fail. I've also removed the pagetwo specs as it would be similar to pageone specs and simplified the pageone specs there.

**Comment by tompascall** [comment]
@Acesmndr which branch have you updated? I cannot find one that contains the jest.config.js file.

**Comment by Acesmndr** [comment]
@tompascall Quite unsure why it was failing yesterday. The registrations wasn't passing the registrationCb function but now that I checked into your fork it's working like a charm. 🤔
Could you merge this PR https://github.com/tompascall/chrome-extension-boilerplate-riot/pull/1 into your fork so that I can cascadedly merge this PR too and start working on all the test specs. 🚀 🎉 🎉

**Comment by tompascall** [comment]
done :)

**Comment by Acesmndr** [comment]
@tompascall Thanks for all the effort you put in! 🙇 🚀 👍

**Pull request merged**
